---

# Installs docker and docker-compose

- name: Add Docker GPG key
  become: true
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present

- name: Install list of packages
  become: true
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'docker-ce', 'docker-compose']
    state: present
    update_cache: yes

