---

- name: Create directory for LDAP stuff
  become: yes
  file:
    path: "/home/ldap"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create directory to store the LDAP configuration
  become: yes
  file:
    path: "/home/ldap/data"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Copy docker Compose definition
  become: yes
  copy:
    src: "ldap_docker-compose.yml"
    dest: "/home/ldap/docker-compose.yml"
    force: no
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rw,g=r,o=r

- name: Copy the LDAP start script
  become: yes
  copy:
    src: "start_ldap.sh"
    dest: "/home/ldap/start_ldap.sh"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rxw,g=r,o=r

- name: Copy the LDAP stop script
  become: yes
  copy:
    src: "stop_ldap.sh"
    dest: "/home/ldap/stop_ldap.sh"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rxw,g=r,o=r

- name: Copy GLauth LDAP config
  become: yes
  copy:
    src: "ldap_config.cfg"
    dest: "/home/ldap/data/config.cfg"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rw,g=r,o=r

- name: start LDAP
  command: "./start_ldap.sh"
  become: yes
  args:
    chdir: /home/ldap

- name: copy ldap test script
  become: yes
  copy:
    src: "test_ldap.sh"
    dest: "/home/ldap/test_ldap.sh"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rwx,g=rx,o=rx

- name: Install ldap-utils (test the LDAP)
  become: true
  apt:
    name: "ldap-utils"
    state: present
    update_cache: yes

- name: retrieve the ldap exec
  become: true
  get_url:
    url: https://github.com/glauth/glauth/releases/download/v1.1.1/glauth64
    dest: "/home/ldap/glauth64"
    owner: "root"
    group: "root"
    mode: u=rwx,g=rx,o=rx
