---

- name: Create directory for LDAP stuff
  become: yes
  file:
    path: "/home/ldap"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create directory to store the LDAP configuration
  become: yes
  file:
    path: "/home/ldap/data"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Copy docker Compose definition
  become: yes
  copy:
    src: "ldap_docker-compose.yml"
    dest: "/home/ldap/docker-compose.yml"
    force: no
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rw,g=r,o=r

# - name: LDAP start script

# - name: LDAP stop script

- name: Copy GLauth LDAP config
  become: yes
  copy:
    src: "ldap_config.cfg"
    dest: "/home/ldap/data/config.cfg"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rw,g=r,o=r

# start ldap