---

# try pinging the system now
- name: Trying if the Ansible communication works now (using a Ping)
  ping:

- name: Gathering facts
  setup:

# Difference between upgrade types: https://askubuntu.com/questions/194651/why-use-apt-get-upgrade-instead-of-apt-get-dist-upgrade
- name: Update the system
  become: true
  apt:
    update-cache: yes
    upgrade: "yes"

- name: set VIMs background to dark by default
  lineinfile:
    path: "/home/ubuntu/.vimrc"
    create: yes
    owner: "ubuntu"
    group: "ubuntu"
    mode: u=rw,g=r,o=r
    insertafter: EOF
    line: ':set background=dark'

- name: Install Docker and Docker-compose binaries
  include_tasks: docker.yml

- name: Install, configure and start the LDAP
  include_tasks: ldap.yml

- name: Install and configure the Nexus
  include_tasks: nexus.yml

# - name: Start setting up the IP Tables
#   include_tasks: roles/general/tasks/iptables-task.yml

# - name: create jenkins user
# - name: add jenkins user to docker group