---

- name: Create directory for Nexus stuff
  become: yes
  file:
    path: "/home/nexus"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Copy docker Compose definition
  become: yes
  copy:
    src: "nexus_docker-compose.yml"
    dest: "/home/nexus/docker-compose.yml"
    force: no
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rw,g=r,o=r

- name: Copy the nexus start script
  become: yes
  copy:
    src: "nexus_start.sh"
    dest: "/home/nexus/nexus_start.sh"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rxw,g=rx,o=r

- name: Copy the nexus stop script
  become: yes
  copy:
    src: "nexus_stop.sh"
    dest: "/home/nexus/ldap_stop.sh"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rxw,g=r,o=r
