---

- name: copy creation groovy script to the target server
  copy:
    src: "configure-client-master.groovy"
    dest: "{{jenkins_cfgmgt_script_dir}}/configure-client-master.groovy"
    force: yes
    mode: u=rw,g=r,o=r

- name: Execute Client Master creation script
  shell: "cat {{jenkins_cfgmgt_script_dir}}/configure-client-master.groovy | {{ CLI_command }} groovy ="
  register: output

- name: Output of Script execution
  debug: 
    var: output.stdout