---
- name: copy creation groovy script to the target server
  copy:
    src: "configure-client-master.groovy"
    dest: "{{jenkins_cfgmgt_script_dir}}/configure-client-master.groovy"
    force: yes
    backup: yes
    mode: u=rw,g=r,o=r

# java -jar jenkins-cli.jar -s http://localhost:8888  -i .ssh/jenkins_cfgMgr_key  -remoting groovy ./jenkins_scripts/configure-client-master.groovy