---

- name: Add the path to the configuration file (.profile)
  become: true
  lineinfile:
    path: "/var/lib/{{ jenkins_user }}/.profile"
    create: yes
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    mode: u=rw,g=r,o=r
    regexp: '^export CASC_JENKINS_CONFIG='
    insertafter: EOF
    line: 'export CASC_JENKINS_CONFIG=/var/lib/{{ jenkins_user }}/cfgAsCode/'

- name: create directory to store the confifuration
  become: true
  file:
    path: "/var/lib/{{ jenkins_user }}/cfgAsCode"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    mode: u=rwx,g=rx,o=rx
    
