---
  - name: Obtaining a list of plugins
    jenkins_script:
      script: 'println(Jenkins.instance.pluginManager.plugins)'
      url: "http://localhost:{{ used_port }}"
      user: "admin"
      password: '{{ jenkins_default_admin_password }}'
    register: output
    
  - debug: 
      var: output.output

  - name: Make sure the plugin is always up-to-date
    jenkins_plugin:
      name: cloudbees-ssh-slaves
      state: latest
      url_username: "admin"
      url_password: '{{ jenkins_default_admin_password }}'
      url: "http://localhost:{{ used_port }}"