---
# This playbook is supposed to run on a system with Docker enabled

- name: Create directory for Nexus stuff
  become: yes
  file:
    path: "/home/nexus"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Copy docker Compose definition
  become: yes
  copy:
    src: "nexus_docker-compose.yml"
    dest: "/home/nexus/docker-compose.yml"
    force: no
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rw,g=r,o=r

- name: Copy the nexus start script
  become: yes
  copy:
    src: "start_nexus.sh"
    dest: "/home/nexus/start_nexus.sh"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rxw,g=rx,o=r

- name: Copy the nexus stop script
  become: yes
  copy:
    src: "stop_nexus.sh"
    dest: "/home/nexus/stop_nexus.sh"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rxw,g=r,o=r

- name: start the Nexus container
  command: "./nexus_start.sh"
  become: yes
  args:
    chdir: /home/nexus