---
# This playbook is supposed to run on a system with Docker enabled

- name: "Include definitions and constants" 
  include_vars: "constants.yml"

- name: Create directory for LDAP stuff
  become: yes
  file:
    path: "{{ ldap_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create directory to store the LDAP configuration
  become: yes
  file:
    path: "{{ ldap_dir }}/data"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Copy docker Compose definition
  become: yes
  copy:
    src: "ldap_docker-compose.yml"
    dest: "{{ ldap_dir }}/docker-compose.yml"
    force: no
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rw,g=r,o=r

- name: Copy the LDAP start script
  become: yes
  copy:
    src: "start_ldap.sh"
    dest: "{{ ldap_dir }}/start_ldap.sh"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rxw,g=r,o=r

- name: Copy the LDAP stop script
  become: yes
  copy:
    src: "stop_ldap.sh"
    dest: "{{ ldap_dir }}/stop_ldap.sh"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rxw,g=r,o=r

- name: Copy GLauth LDAP config
  become: yes
  copy:
    src: "ldap_config.cfg"
    dest: "{{ ldap_dir }}/data/config.cfg"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rw,g=r,o=r

- name: start LDAP
  command: "./start_ldap.sh"
  become: yes
  args:
    chdir: {{ ldap_dir }}

- name: copy ldap test script
  become: yes
  copy:
    src: "test_ldap.sh"
    dest: "{{ ldap_dir }}/test_ldap.sh"
    force: yes
    backup: yes
    owner: "root"
    group: "root"
    mode: u=rwx,g=rx,o=rx

- name: Install ldap-utils (test the LDAP)
  become: true
  apt:
    name: "ldap-utils"
    state: present
    update_cache: yes

