jenkins:
  nodes:
  - permanent:
      labelString: "test"
      mode: NORMAL
      name: "test-agent"
      remoteFS: "/home/jenkins"
      launcher:
        jnlp:
          workDirSettings:
            disabled: true


  # nodes:
  # - permanent:
  #     labelString: "jnlp"
  #     launcher:
  #       jnlp:
  #         workDirSettings:
  #           disabled: false
  #           failIfWorkDirIsMissing: false
  #           internalDir: "remoting"
  #           workDirPath: "C:\\J\\AW"
  #     name: "test-agent"
  #     nodeDescription: "Agent that initiates its own connection to Jenkins"
  #     numExecutors: 3
  #     remoteFS: "/home/jenkins"
  #     retentionStrategy: "always"