jenkins:
  nodes:
  - permanent:
      labelString: "jnlp"
      mode: NORMAL
      name: "jnlp-agent"
      remoteFS: "/home/jenkins"
      launcher:
        jnlp:
          workDirSettings:
            disabled: true
      nodeDescription: "Agent that initiates its own connection to Jenkins"
      retentionStrategy: "always"
  numExecutors: 0
