- hosts: jmm_cjoc

  tasks:
    # - name: create local jenkins_cfg SSH keypair
    #   shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/jenkins_cfg_rsa -q -N ""
    #   args:
    #     creates: ~/.ssh/jenkins_cfg_rsa

    # - name: generate random password
    #   set_fact:
    #     cjoc_password: "{{ lookup('password', '/dev/null') }}"

    # - debug:
    #     msg: "Randomly generated password is : {{ cjoc_password }}"

    - name: load script as variable


