- hosts: jmm_agent_docker

  # this is required as only python3 is installed on Ubuntu AMI (Ansible fails otherwise)
  gather_facts: False

  vars:
    jenkins_node_type: "agent_docker"
    ansible_python_interpreter: auto

  roles:
    - agent_docker


- hosts: jmm_cjoc

  # this is required as only python3 is installed on Ubuntu AMI (Ansible fails otherwise)
  gather_facts: False

  vars:
    jenkins_node_type: "cjoc"
    ansible_python_interpreter: auto

  roles:
    - general
    - jenkins
    #- JCasC


- hosts: jmm_client_master

  # this is required as only python3 is installed on Ubuntu AMI (Ansible fails otherwise)
  gather_facts: False

  vars:
    jenkins_node_type: "master"
    ansible_python_interpreter: auto

  roles:
    - general
    - jenkins  
    #- JCasC  