  
- hosts: jmm_agent_docker

  gather_facts: False

  vars:
    jenkins_node_type: agent_docker"
    ansible_python_interpreter: auto

  # pre_tasks:
  #   - name: "get DNS name for the CJOC endpoint "
  #     command: "terraform output -state=../terraform/terraform.tfstate Jmm_cjoc_dns"
  #     delegate_to: localhost
  #     register: full_cjoc_dns_name

  roles:
    - agent_docker
    - docker_nexus


   