- hosts: jmm_cjoc


  vars:
    jenkins_node_type: "cjoc"
    plugins:
      - 'item1' 
      - 'item2' 
      - 'item3'

  tasks:

    - name: Test that loop works with a manual list
      ping:
        data: '{{item}}'
      loop: "{{ plugins }}"


   